name: Naisi Coupon Auto-Grab

on:
  schedule:
    # 每周三 02:00 UTC = 北京时间 10:00
    - cron: '0 2 * * 3'
  workflow_dispatch:          # 允许手动触发测试

jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run coupon grabber
        env:
          NAISI_USERNAME: ${{ secrets.NAISI_USERNAME }}
          NAISI_PASSWORD: ${{ secrets.NAISI_PASSWORD }}
        run: |
          python coupon.py
